"""Add Objective model for plan objectives

Revision ID: 299cb4966b19
Revises: 601ebd033506
Create Date: 2026-02-20 17:09:06.516618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299cb4966b19'
down_revision = '601ebd033506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='objectivestatus'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('objectives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_objectives_plan_id'), ['plan_id'], unique=False)

    # Skip supervisor_id changes - already handled in previous migration
    # with op.batch_alter_table('students', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_students_supervisor_id'), ['supervisor_id'], unique=False)
    #     batch_op.create_foreign_key('fk_students_supervisor_id', 'users', ['supervisor_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip supervisor_id changes - handled separately
    # with op.batch_alter_table('students', schema=None) as batch_op:
    #     batch_op.drop_constraint('fk_students_supervisor_id', type_='foreignkey')
    #     batch_op.drop_index(batch_op.f('ix_students_supervisor_id'))

    with op.batch_alter_table('objectives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_objectives_plan_id'))

    op.drop_table('objectives')
    # ### end Alembic commands ###
