"""Add StudentPlan and StudentObjective models

Revision ID: 7626744b81ea
Revises: 299cb4966b19
Create Date: 2026-02-21 02:53:44.131269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7626744b81ea'
down_revision = '299cb4966b19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'CANCELLED', 'ON_HOLD', name='planstatus'), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'plan_id', name='unique_student_plan')
    )
    with op.batch_alter_table('student_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_plans_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_plans_student_id'), ['student_id'], unique=False)

    op.create_table('student_objectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_plan_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='objectivestatus'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_plan_id'], ['student_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_objectives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_objectives_student_plan_id'), ['student_plan_id'], unique=False)

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_supervisor_id'), ['supervisor_id'], unique=False)
        batch_op.create_foreign_key('fk_students_supervisor_id', 'users', ['supervisor_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('fk_students_supervisor_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_students_supervisor_id'))

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('student_objectives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_objectives_student_plan_id'))

    op.drop_table('student_objectives')
    with op.batch_alter_table('student_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_plans_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_plans_plan_id'))

    op.drop_table('student_plans')
    # ### end Alembic commands ###
