"""Make plans.student_id nullable

Revision ID: c25183f831a4
Revises: 7626744b81ea
Create Date: 2026-02-21 02:55:20.949148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c25183f831a4'
down_revision = '7626744b81ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_supervisor_id'), ['supervisor_id'], unique=False)
        batch_op.create_foreign_key('fk_students_supervisor_id', 'users', ['supervisor_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('fk_students_supervisor_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_students_supervisor_id'))

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
